### ISSUE TITLE
[QUESTION] Apply more than one role to a resource

### ISSUE THREAD

**Issue by juanwilde** [trivago/jade#18]
I'm facing with the fact that I need to grant access to a resource to more than one role. As I see in the documentation you can only pass an escalar value in roles
```
roles:
    read: ROLE_USER
```

I tried to set a default read role for ADMIN and the in the resource add the role USER but it is not working.

Is there a way to set more than one role? Something like:
```
roles:
    read: [ROLE_USER, ROLE_ANOTHER_USER]
    create: ROLE_USER
```

**Comment by moein** [comment]
@JuanWilde The way jade permission is done is to manage the roles on the hierarchy rather than on the resource
So if you want a resource be accessible for multiple roles you create a role called ROLE_READ_USER and then each ROLE_USER and ROLE_ANOTHER_USER get ROLE_READ_USER in their roles

**Comment by moein** [comment]
@JuanWilde I see you gave a thumbs up so I close this issue 
Thanks
