### ISSUE TITLE
Allow to use return values in ResponseListener

### ISSUE THREAD

**Issue by regniblod** [trivago/jade#7]
In the current implementation of `ListenerManager` the return value of the methods from `ResponseListener` interface are not used, therefore there's no way to include/exclude entities from the response. It can be seen [here](https://github.com/trivago/jade/blob/4d79666b0e8ffc13f99a8f433ac98aea3b60d794/Trivago/Jade/Application/Listener/ListenerManager.php#L416).

IMO `onGetCollectionResponse` should be the only method whose return value should be used since I don't see any use case for using the return value of other methods.

Therefore `ResponseListener` methods signature should like:
- `onGetEntityResponse($entity): void`
- ` onGetCollectionResponse(array $entities): array`
- `onCreateResponse($entity): void`
- `onUpdateResponse($entity): void`

This issue can serve as a discussion about whether or not the return value of this methods should be used.

**Comment by moein** [comment]
It's not a good practice to let the repository bring the data that you don't want to expose.
If you have to hide some data you have 2 options:
1. Create your own repository and modify the logic of fetching
2. In the request listener add the necessary filters
